database:
  base_path:  "C:/Project/New_database/Database"
  years:
    - 2024
  site_name:
    - "HOGG"
  levels:
    - "Clean/SecondStage"
tower_height:
  - 4.09
variables:
  variables_to_read:
    - WS_1_1_1
    - hpbl
    - L
    - V_SIGMA
    - USTAR
    - WD_1_1_1
lat_lon:
  lat: 50.37050
  lon: -100.53390
# -----------------------------
# PIPELINE CONTROL
# -----------------------------
pipeline:
  run_single_ffp: 0
  run_monthly_ffp: 0
  run_ndvi_extraction: 1
  run_plot_ffp: 0
# plot:
#   zoom_radius: 500

# -----------------------------
# GEE SETTINGS (NEW)
# -----------------------------
gee:
  project_id: "ee-joysonuh1"
  scale: 30
  L8: "LANDSAT/LC08/C02/T1_L2"
  L9: "LANDSAT/LC09/C02/T1_L2"

output:
  geotiff_folder: "C:/Project/New_database/NDVI_tif"
  ndvi_csv: "C:/Project/New_database/NDVI_timeseries.csv"
  ndvi_plot: "C:/Project/New_database/NDVI_timeseries.png"

# -----------------------------
# FFP SETTINGS
# -----------------------------
# ffp:
#   required_columns:
#     - WS_1_1_1
#     - hpbl
#     - L
#     - V_SIGMA
#     - USTAR
#     - WD_1_1_1
#     - Zm

#   domain: [-2000, 2000, -2000, 2000]
#   nx: 300
#   ny: 300
#   rs: [20., 40., 60., 80.]

#   min_points: 50
#   smooth_data: 1
#   crop: 0

# -----------------------------
# NDVI SETTINGS (GEE)
# -----------------------------
# ndvi:
#   dataset: "LANDSAT/LC08/C02/T1_L2"
#   dataset_2: "LANDSAT/LC09/C02/T1_L2"

#   method: "all_images"   # options: all_images | monthly_median

#   scale: 30
#   cloud_mask: 1
